package calculadora;

public class Calculadora extends javax.swing.JFrame {

    private boolean igual, inicio = true, operacion1, operacion2;
    private double a, b, c, cos, acos, sin, asin, tan, atan, memoria = 0, resultado, valor1, valor2;
    private String cadena, funciones, tipoOperaciones;

    public Calculadora() {
        initComponents();
        Label_Memoria.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        Label_Memoria = new javax.swing.JLabel();
        TextField_Previo = new javax.swing.JTextField();
        TextField_Principal = new javax.swing.JTextField();
        RadioButton_Sexages = new javax.swing.JRadioButton();
        RadioButton_Radianes = new javax.swing.JRadioButton();
        Button_Cos = new javax.swing.JButton();
        Button_Sin = new javax.swing.JButton();
        Button_Tan = new javax.swing.JButton();
        Button_Retroceso = new javax.swing.JButton();
        Button_C = new javax.swing.JButton();
        Button_Signo = new javax.swing.JButton();
        Button_RaizCuadrada = new javax.swing.JButton();
        Button_CE = new javax.swing.JButton();
        Button_Exponente = new javax.swing.JButton();
        Button_N7 = new javax.swing.JButton();
        Button_N9 = new javax.swing.JButton();
        Button_N8 = new javax.swing.JButton();
        Button_Division = new javax.swing.JButton();
        Button_RaizX = new javax.swing.JButton();
        Button_N5 = new javax.swing.JButton();
        Button_Multiplicacion = new javax.swing.JButton();
        Button_N4 = new javax.swing.JButton();
        Button_N6 = new javax.swing.JButton();
        Button_Resta = new javax.swing.JButton();
        Button_N1 = new javax.swing.JButton();
        Button_Cuadrado = new javax.swing.JButton();
        Button_N3 = new javax.swing.JButton();
        Button_RaizCubica = new javax.swing.JButton();
        Button_N2 = new javax.swing.JButton();
        Button_N0 = new javax.swing.JButton();
        Button_Igual = new javax.swing.JButton();
        Button_Suma = new javax.swing.JButton();
        Button_Decimal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 0, 0));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Label_Memoria.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        Label_Memoria.setText("M");
        getContentPane().add(Label_Memoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 20, -1, -1));

        TextField_Previo.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        TextField_Previo.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextField_Previo.setFocusable(false);
        TextField_Previo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TextField_PrevioActionPerformed(evt);
            }
        });
        getContentPane().add(TextField_Previo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 550, 50));

        TextField_Principal.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        TextField_Principal.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        TextField_Principal.setText("0");
        TextField_Principal.setFocusable(false);
        getContentPane().add(TextField_Principal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 550, 50));

        buttonGroup1.add(RadioButton_Sexages);
        RadioButton_Sexages.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        RadioButton_Sexages.setForeground(new java.awt.Color(255, 255, 255));
        RadioButton_Sexages.setSelected(true);
        RadioButton_Sexages.setText("Sexages");
        getContentPane().add(RadioButton_Sexages, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        buttonGroup1.add(RadioButton_Radianes);
        RadioButton_Radianes.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        RadioButton_Radianes.setForeground(new java.awt.Color(255, 255, 255));
        RadioButton_Radianes.setText("radianes");
        RadioButton_Radianes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioButton_RadianesActionPerformed(evt);
            }
        });
        getContentPane().add(RadioButton_Radianes, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        Button_Cos.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_Cos.setText("cos");
        Button_Cos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CosActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Cos, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 80, 80));

        Button_Sin.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_Sin.setText("sin");
        Button_Sin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SinActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Sin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 150, 80, 80));

        Button_Tan.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_Tan.setText("tan");
        Button_Tan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_TanActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Tan, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 80, 80));

        Button_Retroceso.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_Retroceso.setText("<--");
        Button_Retroceso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RetrocesoActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Retroceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 100, 80));

        Button_C.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_C.setText("C");
        Button_C.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CActionPerformed(evt);
            }
        });
        getContentPane().add(Button_C, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, 80, 80));

        Button_Signo.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        Button_Signo.setText("±");
        Button_Signo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SignoActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Signo, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 80, 80));

        Button_RaizCuadrada.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_RaizCuadrada.setText("√");
        Button_RaizCuadrada.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RaizCuadradaActionPerformed(evt);
            }
        });
        getContentPane().add(Button_RaizCuadrada, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 80, 80));

        Button_CE.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_CE.setText("CE");
        Button_CE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CEActionPerformed(evt);
            }
        });
        getContentPane().add(Button_CE, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 150, 80, 80));

        Button_Exponente.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_Exponente.setText("x^y");
        Button_Exponente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ExponenteActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Exponente, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 100, 80));

        Button_N7.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_N7.setText("7");
        Button_N7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N7ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_N7, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 240, 80, 80));

        Button_N9.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_N9.setText("9");
        Button_N9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N9ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_N9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 240, 80, 80));

        Button_N8.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_N8.setText("8");
        Button_N8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N8ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_N8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 240, 80, 80));

        Button_Division.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_Division.setText("/");
        Button_Division.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DivisionActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Division, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, 80, 80));

        Button_RaizX.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_RaizX.setText("x√y");
        Button_RaizX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RaizXActionPerformed(evt);
            }
        });
        getContentPane().add(Button_RaizX, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 100, 80));

        Button_N5.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_N5.setText("5");
        Button_N5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N5ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_N5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 80, 80));

        Button_Multiplicacion.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        Button_Multiplicacion.setText("*");
        Button_Multiplicacion.setAlignmentY(0.0F);
        Button_Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_MultiplicacionActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Multiplicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 330, 80, 80));

        Button_N4.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_N4.setText("4");
        Button_N4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N4ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_N4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 80, 80));

        Button_N6.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_N6.setText("6");
        Button_N6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N6ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_N6, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 330, 80, 80));

        Button_Resta.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        Button_Resta.setText("-");
        Button_Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RestaActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 420, 80, 80));

        Button_N1.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_N1.setText("1");
        Button_N1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N1ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_N1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 420, 80, 80));

        Button_Cuadrado.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_Cuadrado.setText("x^2");
        Button_Cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_CuadradoActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Cuadrado, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 100, 80));

        Button_N3.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_N3.setText("3");
        Button_N3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N3ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_N3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 420, 80, 80));

        Button_RaizCubica.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_RaizCubica.setText("3√x");
        Button_RaizCubica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_RaizCubicaActionPerformed(evt);
            }
        });
        getContentPane().add(Button_RaizCubica, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 100, 80));

        Button_N2.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_N2.setText("2");
        Button_N2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N2ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_N2, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 420, 80, 80));

        Button_N0.setFont(new java.awt.Font("Segoe UI", 0, 30)); // NOI18N
        Button_N0.setText("0");
        Button_N0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_N0ActionPerformed(evt);
            }
        });
        getContentPane().add(Button_N0, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 170, 80));

        Button_Igual.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        Button_Igual.setText("=");
        Button_Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_IgualActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 80, 170));

        Button_Suma.setFont(new java.awt.Font("Segoe UI", 0, 35)); // NOI18N
        Button_Suma.setText("+");
        Button_Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SumaActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 80, 80));

        Button_Decimal.setFont(new java.awt.Font("Segoe UI", 0, 40)); // NOI18N
        Button_Decimal.setText(".");
        Button_Decimal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_DecimalActionPerformed(evt);
            }
        });
        getContentPane().add(Button_Decimal, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 80, 80));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/imagen.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-740, -240, 1330, 850));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void Trigonometria() {
        if (RadioButton_Sexages.isSelected()) {
            switch (funciones) {
                case "sin":
                    valor1 = Double.parseDouble(TextField_Principal.getText());
                    TextField_Previo.setText(" sin( " + valor1 + " )");
                    sin = Math.sin(Math.PI * (valor1 / 180));
                    TextField_Principal.setText(sin + " ");
                    break;
                case "asin":
                    valor1 = Double.parseDouble(TextField_Principal.getText());
                    TextField_Previo.setText(" asin( " + valor1 + " )");
                    asin = Math.asin(valor1) * 180 / Math.PI;
                    TextField_Principal.setText(asin + " ");
                    break;

                case "cos":
                    valor1 = Double.parseDouble(TextField_Principal.getText());
                    TextField_Previo.setText(" cos( " + valor1 + " )");
                    cos = Math.cos(Math.PI * (valor1 / 180));
                    TextField_Principal.setText(cos + " ");
                    break;
                case "acos":
                    valor1 = Double.parseDouble(TextField_Principal.getText());
                    TextField_Previo.setText(" acos( " + valor1 + " )");
                    acos = Math.acos(valor1) * 180 / Math.PI;
                    TextField_Principal.setText(acos + " ");
                    break;

                case "tan":
                    valor1 = Double.parseDouble(TextField_Principal.getText());
                    TextField_Previo.setText(" tan( " + valor1 + " )");
                    tan = Math.tan(Math.PI * (valor1 / 180));
                    TextField_Principal.setText(tan + " ");
                    break;
                case "atab":
                    valor1 = Double.parseDouble(TextField_Principal.getText());
                    TextField_Previo.setText(" atan( " + valor1 + " )");
                    atan = Math.atan(valor1) * 180 / Math.PI;
                    TextField_Principal.setText(atan + " ");
                    break;

            }
        } else {
            if (RadioButton_Radianes.isSelected()) {
                switch (funciones) {
                    case "sin":
                        valor1 = Double.parseDouble(TextField_Principal.getText());
                        TextField_Previo.setText(" sinR( " + valor1 + " )");
                        sin = Math.sin(valor1);
                        TextField_Principal.setText(sin + " ");
                        break;
                    case "asin":
                        valor1 = Double.parseDouble(TextField_Principal.getText());
                        TextField_Previo.setText(" asinR( " + valor1 + " )");
                        asin = Math.asin(valor1);
                        TextField_Principal.setText(asin + " ");
                        break;

                    case "cos":
                        valor1 = Double.parseDouble(TextField_Principal.getText());
                        TextField_Previo.setText(" cosR( " + valor1 + " )");
                        cos = Math.cos(valor1);
                        TextField_Principal.setText(cos + " ");
                        break;
                    case "acos":
                        valor1 = Double.parseDouble(TextField_Principal.getText());
                        TextField_Previo.setText(" acosR( " + valor1 + " )");
                        acos = Math.acos(valor1);
                        TextField_Principal.setText(acos + " ");
                        break;

                    case "tan":
                        valor1 = Double.parseDouble(TextField_Principal.getText());
                        TextField_Previo.setText(" tanR( " + valor1 + " )");
                        tan = Math.tan(valor1);
                        TextField_Principal.setText(tan + " ");
                        break;
                    case "atab":
                        valor1 = Double.parseDouble(TextField_Principal.getText());
                        TextField_Previo.setText(" atanR( " + valor1 + " )");
                        atan = Math.atan(valor1);
                        TextField_Principal.setText(atan + " ");
                        break;

                }
            }
        }
    }


    private void Button_CosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CosActionPerformed
        funciones = "cos";
        Trigonometria();        // TODO add your handling code here:
    }//GEN-LAST:event_Button_CosActionPerformed

    private void TextField_PrevioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TextField_PrevioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TextField_PrevioActionPerformed

    private void Button_N1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N1ActionPerformed
        if (inicio == true) {
            TextField_Principal.setText("");
            TextField_Principal.setText("1");
            inicio = false;
        } else {
            TextField_Principal.setText(TextField_Principal.getText() + "1");
        }
    }//GEN-LAST:event_Button_N1ActionPerformed

    private void Button_N0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N0ActionPerformed
        if (inicio == true) {
            TextField_Principal.setText("");
            TextField_Principal.setText("0");
            inicio = false;
        } else {
            TextField_Principal.setText(TextField_Principal.getText() + "0");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Button_N0ActionPerformed

    private void Button_N2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N2ActionPerformed
        if (inicio == true) {
            TextField_Principal.setText("");
            TextField_Principal.setText("2");
            inicio = false;
        } else {
            TextField_Principal.setText(TextField_Principal.getText() + "2");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Button_N2ActionPerformed

    private void Button_N3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N3ActionPerformed
        if (inicio == true) {
            TextField_Principal.setText("");
            TextField_Principal.setText("3");
            inicio = false;
        } else {
            TextField_Principal.setText(TextField_Principal.getText() + "3");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Button_N3ActionPerformed

    private void Button_N4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N4ActionPerformed
        if (inicio == true) {
            TextField_Principal.setText("");
            TextField_Principal.setText("4");
            inicio = false;
        } else {
        TextField_Principal.setText(TextField_Principal.getText()+"4");}    }//GEN-LAST:event_Button_N4ActionPerformed

    private void Button_N5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N5ActionPerformed
        if (inicio == true) {
            TextField_Principal.setText("");
            TextField_Principal.setText("5");
            inicio = false;
        } else {
            TextField_Principal.setText(TextField_Principal.getText() + "5");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Button_N5ActionPerformed

    private void Button_N6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N6ActionPerformed
        if (inicio == true) {
            TextField_Principal.setText("");
            TextField_Principal.setText("6");
            inicio = false;
        } else {
        TextField_Principal.setText(TextField_Principal.getText()+"6");}    }//GEN-LAST:event_Button_N6ActionPerformed

    private void Button_N7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N7ActionPerformed
        if (inicio == true) {
            TextField_Principal.setText("");
            TextField_Principal.setText("7");
            inicio = false;
        } else {
            TextField_Principal.setText(TextField_Principal.getText() + "7");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Button_N7ActionPerformed

    private void Button_N8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N8ActionPerformed
        if (inicio == true) {
            TextField_Principal.setText("");
            TextField_Principal.setText("8");
            inicio = false;
        } else {
            TextField_Principal.setText(TextField_Principal.getText() + "8");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Button_N8ActionPerformed

    private void Button_N9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_N9ActionPerformed
        if (inicio == true) {
            TextField_Principal.setText("");
            TextField_Principal.setText("9");
            inicio = false;
        } else {
            TextField_Principal.setText(TextField_Principal.getText() + "9");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_Button_N9ActionPerformed

    private void Button_DecimalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DecimalActionPerformed
        if (TextField_Principal.getText().contains(".")) {

        } else {
            TextField_Principal.setText(TextField_Principal.getText() + ".");
            inicio = false;
        }
    }//GEN-LAST:event_Button_DecimalActionPerformed

    private void Button_SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SumaActionPerformed
        igual = true;
        inicio = true;
        if (operacion1 = true) {
            valor1 = Double.parseDouble(TextField_Principal.getText());
            TextField_Previo.setText("");
            TextField_Previo.setText(TextField_Principal.getText() + "+");
            operacion1 = false;
        } else {
            if (operacion2 = true) {
                valor2 = Double.parseDouble(TextField_Principal.getText());
                TextField_Previo.setText("");
                TextField_Previo.setText(TextField_Principal.getText() + "+");
                operacion2 = false;
            } else {
                TextField_Previo.setText(TextField_Principal.getText() + "+");
                Operaciones(resultado, valor2);
            }
        }
        tipoOperaciones = "+";
    }//GEN-LAST:event_Button_SumaActionPerformed

    private void Button_RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RestaActionPerformed
        igual = true;
        inicio = true;
        if (operacion1 = true) {
            valor1 = Double.parseDouble(TextField_Principal.getText());
            TextField_Previo.setText("");
            TextField_Previo.setText(TextField_Principal.getText() + "-");
            operacion1 = false;
        } else {
            if (operacion2 = true) {
                valor2 = Double.parseDouble(TextField_Principal.getText());
                TextField_Previo.setText("");
                TextField_Previo.setText(TextField_Principal.getText() + "-");
                operacion2 = false;
            } else {
                TextField_Previo.setText(TextField_Principal.getText() + "-");
                Operaciones(resultado, valor2);
            }
        }
tipoOperaciones = "-";    }//GEN-LAST:event_Button_RestaActionPerformed

    private void Button_MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_MultiplicacionActionPerformed
        igual = true;
        inicio = true;
        if (operacion1 = true) {
            valor1 = Double.parseDouble(TextField_Principal.getText());
            TextField_Previo.setText("");
            TextField_Previo.setText(TextField_Principal.getText() + "*");
            operacion1 = false;
        } else {
            if (operacion2 = true) {
                valor2 = Double.parseDouble(TextField_Principal.getText());
                TextField_Previo.setText("");
                TextField_Previo.setText(TextField_Principal.getText() + "*");
                operacion2 = false;
            } else {
                TextField_Previo.setText(TextField_Principal.getText() + "*");
                Operaciones(resultado, valor2);
            }
        }
tipoOperaciones = "*";    }//GEN-LAST:event_Button_MultiplicacionActionPerformed

    private void Button_DivisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_DivisionActionPerformed
        igual = true;
        inicio = true;
        if (operacion1 = true) {
            valor1 = Double.parseDouble(TextField_Principal.getText());
            TextField_Previo.setText("");
            TextField_Previo.setText(TextField_Principal.getText() + "/");
            operacion1 = false;
        } else {
            if (operacion2 = true) {
                valor2 = Double.parseDouble(TextField_Principal.getText());
                TextField_Previo.setText("");
                TextField_Previo.setText(TextField_Principal.getText() + "/");
                operacion2 = false;
            } else {
                TextField_Previo.setText(TextField_Principal.getText() + "/");
                Operaciones(resultado, valor2);
            }
        }
        tipoOperaciones = "/";        // TODO add your handling code here:
    }//GEN-LAST:event_Button_DivisionActionPerformed

    private void Operaciones(double valor1, double valor2) {
        switch (tipoOperaciones) {
            case "+":
                resultado = valor1 + valor2;
                TextField_Principal.setText(resultado + "");
                valor1 = Double.parseDouble(TextField_Principal.getText());
                break;
            case "-":
                resultado = valor1 - valor2;
                TextField_Principal.setText(resultado + "");
                valor1 = Double.parseDouble(TextField_Principal.getText());
                break;
            case "*":
                resultado = valor1 * valor2;
                TextField_Principal.setText(resultado + "");
                valor1 = Double.parseDouble(TextField_Principal.getText());
                break;
            case "/":
                if (valor2 == 0) {
                    TextField_Principal.setText("Error!!!!");
                    break;
                } else {

                    resultado = valor1 / valor2;
                    TextField_Principal.setText(resultado + "");
                    valor1 = Double.parseDouble(TextField_Principal.getText());
                    break;
                }
            case "potencia":
                resultado = Math.pow(valor1, valor2);
                TextField_Principal.setText(resultado + " ");
                break;

            case "raizx":
                if (valor2 <= 0) {
                    TextField_Principal.setText("Error!!!");
                } else {
                    TextField_Previo.setText(valor1 + "√ ");
                    a = 1;
                    c = a / valor1;
                    TextField_Principal.setText(Math.pow(valor2, c) + " ");
                    break;
                }
        }
    }
    private void Button_IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_IgualActionPerformed
        inicio = true;
        operacion1 = true;
        if (igual = true) {
            if (tipoOperaciones == null) {
            } else {
                valor2 = Double.parseDouble(TextField_Principal.getText());
                TextField_Previo.setText(TextField_Previo.getText() + TextField_Principal.getText());
                Operaciones(valor1, valor2);
                igual = false;
            }
        } else {
            TextField_Previo.setText("");
            Operaciones(valor1, valor2);
        }
    }//GEN-LAST:event_Button_IgualActionPerformed

    private void Button_RaizCuadradaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RaizCuadradaActionPerformed
        valor1 = Double.parseDouble(TextField_Principal.getText());
        if (valor1 >= 0) {
            TextField_Previo.setText("√( " + valor1 + " )");
            TextField_Principal.setText(Math.sqrt(valor1) + " ");
        } else {
            TextField_Principal.setText("Error!!!");
        }
    }//GEN-LAST:event_Button_RaizCuadradaActionPerformed

    private void Button_SignoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SignoActionPerformed
        double nu1 = 0, nu2, nu3;
        nu2 = Double.parseDouble(TextField_Principal.getText());
        nu3 = nu1 - nu2;
        TextField_Principal.setText(nu3 + " ");
    }//GEN-LAST:event_Button_SignoActionPerformed

    private void Button_CActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CActionPerformed
        TextField_Principal.setText("0");
        TextField_Previo.setText("");
        inicio = true;
        funciones = "";
        operacion1 = true;
        operacion2 = true;
        igual = true;
        valor1 = 0;
        valor2 = 0;
        resultado = 0;
    }//GEN-LAST:event_Button_CActionPerformed

    private void Button_CEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CEActionPerformed
        TextField_Principal.setText("0");
        TextField_Previo.setText("");
        inicio = true;
        funciones = "";
    }//GEN-LAST:event_Button_CEActionPerformed

    private void Button_RetrocesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RetrocesoActionPerformed
        if (TextField_Principal.getText().length() > 0) {
            TextField_Principal.setText(TextField_Principal.getText().substring(0, TextField_Principal.getText().length() - 1));
            if (TextField_Principal.getText().length() == 0) {
                TextField_Principal.setText("0");
                inicio = true;
            }
        }
    }//GEN-LAST:event_Button_RetrocesoActionPerformed

    private void Button_SinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SinActionPerformed
        funciones = "sin";
        Trigonometria();      }//GEN-LAST:event_Button_SinActionPerformed

    private void Button_TanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_TanActionPerformed
        funciones = "tan";
        Trigonometria();          // TODO add your handling code here:
    }//GEN-LAST:event_Button_TanActionPerformed

    private void Button_ExponenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ExponenteActionPerformed
        inicio = true;
        valor1 = Double.parseDouble(TextField_Principal.getText());
        TextField_Previo.setText(valor1 + "^");
        tipoOperaciones = "potencia";
        operacion1 = false;
        igual = true;

    }//GEN-LAST:event_Button_ExponenteActionPerformed

    private void Button_RaizXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RaizXActionPerformed
        inicio = true;
        valor1 = Double.parseDouble(TextField_Principal.getText());
        TextField_Previo.setText(valor1 + "√ ");
        tipoOperaciones = "raizx";
        operacion1 = false;
        igual = true;


    }//GEN-LAST:event_Button_RaizXActionPerformed

    private void Button_RaizCubicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_RaizCubicaActionPerformed
        valor1 = Double.parseDouble(TextField_Principal.getText());
        a = 1;
        b = 3;
        c = a / b;
        TextField_Previo.setText("3√( " + valor1 + " )");
        TextField_Principal.setText(Math.pow(valor1, c) + " ");
    }//GEN-LAST:event_Button_RaizCubicaActionPerformed

    private void Button_CuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_CuadradoActionPerformed
        valor1 = Double.parseDouble(TextField_Principal.getText());
        TextField_Previo.setText("elevando al cuadrado el número( " + valor1 + " )");
        TextField_Principal.setText(Math.pow(valor1, 2) + " ");
    }//GEN-LAST:event_Button_CuadradoActionPerformed

    private void RadioButton_RadianesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioButton_RadianesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RadioButton_RadianesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_C;
    private javax.swing.JButton Button_CE;
    private javax.swing.JButton Button_Cos;
    private javax.swing.JButton Button_Cuadrado;
    private javax.swing.JButton Button_Decimal;
    private javax.swing.JButton Button_Division;
    private javax.swing.JButton Button_Exponente;
    private javax.swing.JButton Button_Igual;
    private javax.swing.JButton Button_Multiplicacion;
    private javax.swing.JButton Button_N0;
    private javax.swing.JButton Button_N1;
    private javax.swing.JButton Button_N2;
    private javax.swing.JButton Button_N3;
    private javax.swing.JButton Button_N4;
    private javax.swing.JButton Button_N5;
    private javax.swing.JButton Button_N6;
    private javax.swing.JButton Button_N7;
    private javax.swing.JButton Button_N8;
    private javax.swing.JButton Button_N9;
    private javax.swing.JButton Button_RaizCuadrada;
    private javax.swing.JButton Button_RaizCubica;
    private javax.swing.JButton Button_RaizX;
    private javax.swing.JButton Button_Resta;
    private javax.swing.JButton Button_Retroceso;
    private javax.swing.JButton Button_Signo;
    private javax.swing.JButton Button_Sin;
    private javax.swing.JButton Button_Suma;
    private javax.swing.JButton Button_Tan;
    private javax.swing.JLabel Label_Memoria;
    private javax.swing.JRadioButton RadioButton_Radianes;
    private javax.swing.JRadioButton RadioButton_Sexages;
    private javax.swing.JTextField TextField_Previo;
    private javax.swing.JTextField TextField_Principal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

    String sincero(float resultado) {
        throw new UnsupportedOperationException("Not supported yet.");
    }
}
